name: Scrape local newspapers

on:
  schedule:
    - cron: '3,8,13,18,23,28,33,38,43,48,53,58 * * * *'
  workflow_dispatch:

jobs:
  run_script_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Execute local_news.py
        run: python local_news.py
        env:
          WEBHOOK_OSTFOLD: ${{ secrets.WEBHOOK_OSTFOLD }}
          WEBHOOK_BUSKERUD: ${{ secrets.WEBHOOK_BUSKERUD }}
          WEBHOOK_OSLO_AKERSHUS: ${{ secrets.WEBHOOK_OSLO_AKERSHUS }}
          WEBHOOK_ERROR: ${{ secrets.WEBHOOK_ERROR }}

      - name: Check for changes
        id: git_status
        run: |
          if ! git diff --quiet; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Commit and push if changes exist
        if: steps.git_status.outputs.has_changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          timestamp=$(date -u)
          git commit -m "Updated: ${timestamp}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}